FROM kibana:5.2.1
#COPY 0cebf3d61338c454670b1c5bdf5d6d8d.svg /usr/share/kibana/optimize/bundles/0cebf3d61338c454670b1c5bdf5d6d8d.svg
#COPY commons.style.css /usr/share/kibana/optimize/bundles/commons.style.css
#COPY chrome.jade /usr/share/kibana/src/ui/views
#COPY ui_app.jade /usr/share/kibana/src/ui/views
#COPY kibana.svg /usr/share/kibana/src/ui/public/images/kibana.svg
#COPY favicon.ico /usr/share/kibana/src/ui/public/views/favicon.ico
